//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesWebSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodType()
        {
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int FoodTypeID { get; set; }
        public string FoodType1 { get; set; }
        public string FoodTypeImg { get; set; }
        public Nullable<bool> FoodTypeStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
        public virtual FoodTypeStatus FoodTypeStatus { get; set; }
    }
}
