//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesWebSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public Nullable<bool> UserStatusID { get; set; }
        public Nullable<byte> UserLevelID { get; set; }
        public string UserNickname { get; set; }
        public string UserPassword { get; set; }
    
        public virtual UserLevel UserLevel { get; set; }
        public virtual UserStatus UserStatus { get; set; }
    }
}
